project:
  type: book

book:
  title: "Pencarian & Penambangan Web"
  output-file: "quarto-crc"
  author: "Zuni Amanda Dewi (200411100051)"

  chapters:
    - index.qmd
    - scraping_pta.ipynb
    - Preprocessing_dan_Ekstraksi_Fitur.ipynb
    - LDA_Topic_Modelling.ipynb
    - scraping_suararakyat.ipynb
    - Klasifikasi_dengan_Ringkasan.ipynb
    - ekstraksi_kata_kunci.ipynb
    - UAS.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: krantz
    keep-tex: true
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
